select CR.Author_Id_Number "DO"
       , BIO.SORT_NAME "DO Name"
       , COUNT(CASE WHEN CR.AUTHOR_ID_NUMBER = S.ID_NUMBER THEN 1 ELSE NULL END) "Visits By RM"
       , COUNT(CASE WHEN CR.AUTHOR_ID_NUMBER <> S.ID_NUMBER THEN 1 ELSE NULL END) "Visits By Non RM"
       , COUNT(CASE WHEN S.ID_NUMBER IS NULL THEN 1 ELSE NULL END) "Prospects With No RM Visits"
       , COUNT(CASE WHEN ASGMT.PRIORITY_CODE = 'PQ' THEN 1 ELSE NULL END) "Visits Not PQ"
       , SYSDATE AS "Date Pulled"
       , '7/1/2015 - 5/15/2017' AS "Data Date Range"
from ADVANCE.CONTACT_REPORT CR
     LEFT OUTER JOIN ADVANCE.PROSPECT P
          ON P.Prospect_Id = CR.Prospect_Id
     LEFT OUTER JOIN ADVANCE.ASSIGNMENT ASGMT
          ON P.PROSPECT_ID = ASGMT.PROSPECT_ID AND ASGMT.ACTIVE_IND = 'Y' AND ASGMT.ASSIGNMENT_TYPE = 'LM'
     LEFT OUTER JOIN ADVANCE.STAFF S
           ON ASGMT.ASSIGNMENT_ID_NUMBER = S.ID_NUMBER 
     LEFT OUTER JOIN ADVANCE.UCDR_BIO BIO
           ON CR.Author_Id_Number = BIO.ID_NUMBER 
WHERE (CR.CONTACT_TYPE = 'V' OR (CR.CONTACT_TYPE in ('C', 'P') and CR.Contact_Initiated_By = 'FCGS'))
          AND CR.CONTACT_DATE BETWEEN TO_DATE('7/1/2015', 'MM/DD/YYYY') AND TO_DATE('5/15/2017', 'MM/DD/YYYY')
GROUP BY CR.Author_Id_Number
       , BIO.SORT_NAME
ORDER BY BIO.SORT_NAME
